name: Personal Website Workflows

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_REGISTRY: forgejo.akmal-maulana.my.id
  USER_REGISTRY: ${{ secrets.USER_SELENA }}
  TOKEN_REGISTRY: ${{ secrets.TOKEN_SELENA }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: https://github.com/actions/checkout@v3

      - name: Log in to Registry
        uses: https://github.com/docker/login-action@v2
        with:
          username: ${{ env.USER_REGISTRY }}
          password: ${{ env.TOKEN_REGISTRY }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Build Image
        id: build-image
        uses: https://github.com/docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_REGISTRY}}/selena/personal-website:latest
