name: Personal Website Workflows

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_REGISTRY: git.akmalmaulana.net
  USER_REGISTRY: ${{ secrets.USER_AKMAL }}
  TOKEN_REGISTRY: ${{ secrets.TOKEN_AKMAL }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: https://github.com/actions/checkout@v3

      - name: Log in to Registry
        uses: https://github.com/docker/login-action@v2
        with:
          username: ${{ env.USER_REGISTRY }}
          password: ${{ env.TOKEN_REGISTRY }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Build Image
        id: build-image
        uses: https://github.com/docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_REGISTRY}}/akmalm007/personal-website:latest

      - name: Deploy
        id: deployments
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY}}
          USER: ${{ secrets.VPS_USER}}
          IP: ${{ secrets.VPS_IP}}
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

          # Run Deployment
          ssh $USER@$IP
