name: Blog

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: gitea.akmal-maulana.my.id
          username: ${{ secrets.USER_LUNA }}
          password: ${{ secrets.TOKEN_LUNA }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: gitea.akmal-maulana.my.id/luna/personal-website:latest

      - name: Deployment
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY}}
          USER: ${{ secrets.VPS_USER}}
          IP: ${{ secrets.VPS_IP}}
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" >> ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

          # Run Deployment
          ssh -i ~/.ssh/deploy_key $USER@$IP
